### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by oskarirauta**
Check commits and commit messages.

### CODE REVIEW

**Comment by oskarirauta** [comment]
There's still this warning on build:

```
/usr/src/openwrt/build_dir/target-x86_64_musl/linux-x86_64/beadapanel-1.0-1/beada.c:97:61: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   97 |                         sprintf(binstr, "%08x -", i + (int)addr);
```

**Comment by JT365** [comment]
This driver is still experimental and changing dynamically. So I would like choose some of the commits to merge. This branch for parking the patch.

**Comment by JT365** [comment]
This branch for parking the patch.

**Comment by oskarirauta** [comment]
Yes, parts of these are concepts and ideas. Though, removing unused variables and functions is not a bad choice, I also would recommend the cast fix. Time set from local system time on modprobe is nice thought, but I couldn't make it work (at least clock on screen did not change)

**Comment by JT365** [comment]
I would suggest you to implement these backlight & systime features in sysfs space, if you have spare time and interests to this project.

**Pull request merged**
